# fly.toml app configuration file generated for bjj-ecom-tgc-proj3-express on 2023-07-22T15:39:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bjj-ecom-tgc-proj3-express"
primary_region = "sin"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
